config/routes.rb
Rails.application.routes.draw do

  resources :shippings
  resources :orders
  devise_for :users
  resources :line_items
  resources :carts
  resources :photographs
  resources :photo_catagories
  resources :homes
  resources :charges
root 'homes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/shipping.rb
class Shipping < ApplicationRecord
  belongs_to :order
end

app/controllers/shippings_controller.rb
class ShippingsController < ApplicationController
  before_action :set_shipping, only: [:show, :edit, :update, :destroy]

  # GET /shippings
  # GET /shippings.json
  def index
    @shippings = Shipping.all
  end

  # GET /shippings/1
  # GET /shippings/1.json
  def show
  end

  # GET /shippings/new
  def new
    @shipping = Shipping.new
  end

  # GET /shippings/1/edit
  def edit
  end

  # POST /shippings
  # POST /shippings.json
  def create
    @shipping = Shipping.new(shipping_params)

    respond_to do |format|
      if @shipping.save
        format.html { redirect_to @shipping, notice: 'Shipping was successfully created.' }
        format.json { render :show, status: :created, location: @shipping }
      else
        format.html { render :new }
        format.json { render json: @shipping.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shippings/1
  # PATCH/PUT /shippings/1.json
  def update
    respond_to do |format|
      if @shipping.update(shipping_params)
        format.html { redirect_to @shipping, notice: 'Shipping was successfully updated.' }
        format.json { render :show, status: :ok, location: @shipping }
      else
        format.html { render :edit }
        format.json { render json: @shipping.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shippings/1
  # DELETE /shippings/1.json
  def destroy
    @shipping.destroy
    respond_to do |format|
      format.html { redirect_to shippings_url, notice: 'Shipping was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shipping
      @shipping = Shipping.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shipping_params
      params.require(:shipping).permit(:name, :cost, :order_id)
    end
end

app/helpers/shipping_helper.rb
module ShippingHelper
end

app/helpers/shippings_helper.rb
module ShippingsHelper
end

app/views/shippings/_form.html.erb
<%= simple_form_for(@shipping) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :cost %>
    <%= f.association :order %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/shippings/edit.html.erb
<h1>Editing Shipping</h1>

<%= render 'form', shipping: @shipping %>

<%= link_to 'Show', @shipping %> |
<%= link_to 'Back', shippings_path %>

app/views/shippings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shippings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cost</th>
      <th>Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shippings.each do |shipping| %>
      <tr>
        <td><%= shipping.name %></td>
        <td><%= shipping.cost %></td>
        <td><%= shipping.order %></td>
        <td><%= link_to 'Show', shipping %></td>
        <td><%= link_to 'Edit', edit_shipping_path(shipping) %></td>
        <td><%= link_to 'Destroy', shipping, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shipping', new_shipping_path %>

app/views/shippings/new.html.erb
<h1>New Shipping</h1>

<%= render 'form', shipping: @shipping %>

<%= link_to 'Back', shippings_path %>

app/views/shippings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @shipping.name %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @shipping.cost %>
</p>

<p>
  <strong>Order:</strong>
  <%= @shipping.order %>
</p>

<%= link_to 'Edit', edit_shipping_path(@shipping) %> |
<%= link_to 'Back', shippings_path %>