config/routes.rb
Rails.application.routes.draw do

  resources :shippings
  resources :orders
  devise_for :users
  resources :line_items
  resources :carts
  resources :photographs
  resources :photo_catagories
  resources :homes
  resources :charges
root 'homes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy


def add_product(photograph_id, size)
      current_item = line_items.find_by(photograph_id: photograph_id, size: size)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(photograph_id: photograph_id)
    end
  current_item
end

def total_price
  line_items.to_a.sum { |item| item.total_price }
end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]



  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
      @photographs = Photograph.all
      @line_items = LineItem.all
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Cart was emptied.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
                <% @cart.line_items.each do |item| %>
              <div class="cart_col">
                <div>
                  <div class="card card-inverse">
                    <img class="card-img" src="<%= item.photograph.image %>" width="375px" height="250px" alt="item.photograph.title">
                    <div class="card-img-overlay">
                      <h4 class"card-title"> <%= item.photograph.title %> </h4>
                      <p> <%= item.quantity %> <%= item.size %> <%= "print".pluralize(item.quantity) %> in cart </p>
                      <p> <%= number_to_currency (item.price * item.quantity) %> </p>
                    </div>
                  </div>
                </div>
              </div>

                <% end %>

app/views/carts/_cart_price.html.erb
<div class="container">

 <h2> Total Price: <%= number_to_currency (@cart.total_price) %> </h2>




  <%= link_to 'Empty cart', @cart, method: :delete,
  data: {confirm: 'Are you sure?'}, class: "btn btn-danger" %>
</div>

app/views/carts/_form.html.erb
<%= simple_form_for(@cart) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>
<%= content_for :header_photo, "http://i.imgur.com/lgZirLX.jpg" %>

<header class="intro">
    <div class="intro-body">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <h1 class="brand-heading">Your Cart</h1>
                </div>
                    <%= render "cart" %>
            </div>
            <h2> Total Price: <%= number_to_currency (@cart.total_price) %> </h2>
            <%= button_to 'Empty cart', @cart, method: :delete,
            data: {confirm: 'Are you sure?'}, class: "btn btn-danger" %>
        </div>
    </div>
</header>

<!-- Styles section -->

<section id="download" class ="container content-section text-center">
  <%= render "photographs/photo_loop" %>

            <!-- About Section -->
            <section id="about" class="container content-section text-center">
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2">
                        <h2>About the photographer</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed justo turpis, euismod vel luctus quis, mattis non nisi.</p>
                        <p> Suspendisse eget ex facilisis, tempor risus et, porta tellus. </p>
                        <p>Mauris in dolor vel orci bibendum scelerisque. Quisque nec finibus justo, id imperdiet nisi. Praesent at arcu vitae orci feugiat sollicitudin.</p>
                    </div>
                </div>
            </section>




            <!-- Contact Section -->
            <section id="contact" class="container content-section text-center">
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2">
                        <h2>Contact Start Bootstrap</h2>
                        <p>Feel free to email us to provide some feedback on our templates, give us suggestions for new templates and themes, or to just say hello!</p>
                        <p><a href="mailto:feedback@startbootstrap.com">feedback@startbootstrap.com</a>
                        </p>
                        <ul class="list-inline banner-social-buttons">
                            <li>
                                <a href="https://twitter.com/SBootstrap" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                            </li>
                            <li>
                                <a href="https://github.com/IronSummitMedia/startbootstrap" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                            </li>
                            <li>
                                <a href="https://plus.google.com/+Startbootstrap/posts" class="btn btn-default btn-lg"><i class="fa fa-google-plus fa-fw"></i> <span class="network-name">Google+</span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </section>

            <!-- Map Section -->
            <div id="map"></div>

            <!-- Footer -->
            <footer>
                <div class="container text-center">
                    <p>Joel Davison 2016</p>
                </div>
            </footer>