config/routes.rb
Rails.application.routes.draw do

  resources :shippings
  resources :orders
  devise_for :users
  resources :line_items
  resources :carts
  resources :photographs
  resources :photo_catagories
  resources :homes
  resources :charges
root 'homes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/photograph.rb
class Photograph < ApplicationRecord
  belongs_to :photo_catagory
  has_many :line_items
resourcify
  before_destroy :ensure_not_referenced_by_any_line_item
  #...

  private

  #ensure that there are no line items referencing this product
  def ensure_not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, 'Line Items present')
      throw :abort
    end
  end
end

app/controllers/photographs_controller.rb
class PhotographsController < ApplicationController
  before_action :set_photograph, only: [:show, :edit, :update, :destroy]
load_and_authorize_resource
  # GET /photographs
  # GET /photographs.json
  def index
    @photographs = Photograph.all
      @photo = Photograph.find(1)
  end

  # GET /photographs/1
  # GET /photographs/1.json
  def show
    @photographs = Photograph.all
  end

  # GET /photographs/new
  def new
    @photograph = Photograph.new
  end

  # GET /photographs/1/edit
  def edit
  end

  # POST /photographs
  # POST /photographs.json
  def create
    @photograph = Photograph.new(photograph_params)

    respond_to do |format|
      if @photograph.save
        format.html { redirect_to @photograph, notice: 'Photograph was successfully created.' }
        format.json { render :show, status: :created, location: @photograph }
      else
        format.html { render :new }
        format.json { render json: @photograph.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photographs/1
  # PATCH/PUT /photographs/1.json
  def update
    respond_to do |format|
      if @photograph.update(photograph_params)
        format.html { redirect_to @photograph, notice: 'Photograph was successfully updated.' }
        format.json { render :show, status: :ok, location: @photograph }
      else
        format.html { render :edit }
        format.json { render json: @photograph.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photographs/1
  # DELETE /photographs/1.json
  def destroy
    @photograph.destroy
    respond_to do |format|
      format.html { redirect_to photographs_url, notice: 'Photograph was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photograph
      @photograph = Photograph.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photograph_params
      params.require(:photograph).permit(:title, :image, :descritpion, :active, :is_cover, :order, :price_small, :price, :price_large, :price_xlarge, :photo_catagory_id)
    end
end

app/helpers/photographs_helper.rb
module PhotographsHelper
end

app/views/photographs/_form.html.erb
<%= simple_form_for(@photograph) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :image %>
    <%= f.input :descritpion %>
    <%= f.input :active %>
    <%= f.input :is_cover %>
    <%= f.input :order %>
    <%= f.input :price_small %>
    <%= f.input :price %>
    <%= f.input :price_large %>
    <%= f.input :price_xlarge %>
    <%= f.association :photo_catagory %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/photographs/_photo_loop.html.erb
  <div class="row">
    <% @photographs.each do |photo| %>
      <div class="col-md-4">
        <div class="card card-inverse">
          <a href="<%= photograph_path(photo.id) %>">
          <img class="card-img" src="<%= photo.image %>" width="100%" height="210px" alt="photograph.catagory">
          </a>
          <div class="card-img-overlay">
            <h4 class"card-title"> <%= photo.title %> </h4>
          </div>
        </div>
        </div>
      <% end %>
  </div>

app/views/photographs/edit.html.erb
<h1>Editing Photograph</h1>

<%= render 'form', photograph: @photograph %>

<%= link_to 'Show', @photograph %> |
<%= link_to 'Back', photographs_path %>

app/views/photographs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Photographs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Image</th>
      <th>Descritpion</th>
      <th>Active</th>
      <th>Is cover</th>
      <th>Order</th>
      <th>Price</th>
      <th>Photo catagory</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photographs.each do |photograph| %>
      <tr>
        <td><%= photograph.title %></td>
        <td><%= photograph.image %></td>
        <td><%= photograph.descritpion %></td>
        <td><%= photograph.active %></td>
        <td><%= photograph.is_cover %></td>
        <td><%= photograph.order %></td>
        <td><%= photograph.price %></td>
        <td><%= photograph.photo_catagory %></td>
        <td><%= link_to 'Show', photograph %></td>
        <td><%= link_to 'Edit', edit_photograph_path(photograph) %></td>
        <td><%= link_to 'Destroy', photograph, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photograph', new_photograph_path %>

app/views/photographs/new.html.erb
<h1>New Photograph</h1>

<%= render 'form', photograph: @photograph %>

<%= link_to 'Back', photographs_path %>

app/views/photographs/show.html.erb
<p id="notice"><%= notice %></p>
<%= content_for :header_photo, @photograph.image %>


<header class="intro">
    <div class="intro-body">
        <div class="container" style="background-color: rgba(0, 0, 0, 0.7); border-radius: 25px;">
            <div class="row">
                <div class="col-md-8 col-md-offset-2 " >
                    <h1 class="brand-heading"><%= @photograph.title %></h1>
                    <p class="intro-text"><%= @photograph.descritpion %></p>
                    <button data-toggle="collapse" data-target="#prints" class="btn btn-info">Purchase a print</button>
                </div>
                <div id="prints" class="collapse">
                <div class="col-md-3">
                  <p> Buy a small sized print for <%= number_to_currency(@photograph.price_small) %> </p>
                  <%= button_to 'Add to cart', line_items_path(photograph_id: @photograph, size: "small", price: @photograph.price_small), class: "btn btn-primary" %>
                </div>
                <div class="col-md-3">
                  <p> Buy a regular sized print for <%= number_to_currency(@photograph.price) %> </p>
                  <%= button_to 'Add to cart', line_items_path(photograph_id: @photograph, size: "regular", price: @photograph.price), class: "btn btn-primary" %>
                </div>
                <div class="col-md-3">
                  <p> Buy a large sized print for <%= number_to_currency(@photograph.price_large) %> </p>
                  <%= button_to 'Add to cart', line_items_path(photograph_id: @photograph, size: "large", price: @photograph.price_large), class: "btn btn-primary" %>
                </div>
                <div class="col-md-3">
                  <p> Buy an extra large sized print for <%= number_to_currency(@photograph.price_xlarge) %> </p>
                  <%= button_to 'Add to cart', line_items_path(photograph_id: @photograph, size: "xlarge", price: @photograph.price_xlarge), class: "btn btn-primary" %>
                </div>
                <div class="col-md-8 col-md-offset-2">
                    <button data-toggle="collapse" data-target="#print_info" class="btn btn-link">Print specifications</button>
                    <div id="print_info" class="collpase"> Information about prints will go here.</div>
                </div>
                </div>
            </div>
            <br>

        </div>
        <br>
        <a href="#download" class="btn btn-circle page-scroll">
            <i class="fa fa-angle-double-down animated"></i>
        </a>
    </div>
</header>

<!-- Styles section -->

<section id="download" class ="container content-section text-center">
<%= render "photo_loop" %>

            <!-- About Section -->
            <section id="about" class="container content-section text-center">
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2">
                        <h2>About the photographer</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed justo turpis, euismod vel luctus quis, mattis non nisi.</p>
                        <p> Suspendisse eget ex facilisis, tempor risus et, porta tellus. </p>
                        <p>Mauris in dolor vel orci bibendum scelerisque. Quisque nec finibus justo, id imperdiet nisi. Praesent at arcu vitae orci feugiat sollicitudin.</p>
                    </div>
                </div>
            </section>




            <!-- Contact Section -->
            <section id="contact" class="container content-section text-center">
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2">
                        <h2>Contact Start Bootstrap</h2>
                        <p>Feel free to email us to provide some feedback on our templates, give us suggestions for new templates and themes, or to just say hello!</p>
                        <p><a href="mailto:feedback@startbootstrap.com">feedback@startbootstrap.com</a>
                        </p>
                        <ul class="list-inline banner-social-buttons">
                            <li>
                                <a href="https://twitter.com/SBootstrap" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                            </li>
                            <li>
                                <a href="https://github.com/IronSummitMedia/startbootstrap" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                            </li>
                            <li>
                                <a href="https://plus.google.com/+Startbootstrap/posts" class="btn btn-default btn-lg"><i class="fa fa-google-plus fa-fw"></i> <span class="network-name">Google+</span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </section>

            <!-- Map Section -->
            <div id="map"></div>

            <!-- Footer -->
            <footer>
                <div class="container text-center">
                    <p>Joel Davison 2016</p>
                </div>
            </footer>